---
title: "Ampliseq: exclude Danish"
author: "Alexey Larionov"
date: "04 Mar 2021"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: true
editor_options:
  chunk_output_type: console
---

# Summary  

Remove 125 danish samples. Then exclude 321 non-polymorphic sites appeared after the samples removal,   

Input data: 3,675 vars x 515 samples (258UBC + 257CBC)  
Output data: 3,354 vars x 390 samples (195UBC + 195CBC)  

# Start section

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r echo=F}
options(width = 999)
```

```{r}

# Time stamp
Sys.time()

# Clenan-up
rm(list=ls())
graphics.off()

# Memory
gc()

# Options
options(stringsAsFactors = F,
        warnPartialMatchArgs = T, 
        warnPartialMatchAttr = T, 
        warnPartialMatchDollar = T)

# Files and folders
base_folder="/Users/alexey/Documents/wecare/final_analysis_2021/reanalysis_wo_danish_2021/ampliseq/s01_ampliseq_wecare_only"
data_folder <- file.path(base_folder,"data","s10_filter_samples")
scripts_folder <- file.path(base_folder,"scripts","s10_filter_samples")
setwd(scripts_folder)

```

# Read data  

```{r}

# Load data
load(file.path(data_folder,"s03_exclude_BRCA1_BCRA2_PALB2_carriers.RData"))

# Update folders
base_folder="/Users/alexey/Documents/wecare/final_analysis_2021/reanalysis_wo_danish_2021/ampliseq/s01_ampliseq_wecare_only"
data_folder <- file.path(base_folder,"data","s10_filter_samples")
scripts_folder <- file.path(base_folder,"scripts","s10_filter_samples")

```

# Check data

```{r}

ls()

dim(genotypes.mx)
dim(phenotypes.df)
dim(variants.df)

sum(colnames(genotypes.mx) != rownames(phenotypes.df))
sum(rownames(genotypes.mx) != rownames(variants.df))

```

# Remove danish samples  

```{r}

# Check data
table(phenotypes.df$cc)
table(phenotypes.df$danish)
table(phenotypes.df[,c("cc","danish")])

# Remove danish
selected_cases <- ! phenotypes.df$danish
sum(selected_cases)

genotypes.mx <- genotypes.mx[,selected_cases]
phenotypes.df <- phenotypes.df[selected_cases,]

# Check result
dim(genotypes.mx)
dim(variants.df)

table(phenotypes.df$cc)
table(phenotypes.df$danish)
table(phenotypes.df[,c("cc","danish")])

# Clean-up
rm(selected_cases)

```

# Remove non-polymorphic sites

```{r}

# Function to detect uniform numeric vector
uniformity_check.udf <- function(x){
  if (all(is.na(x))){"All_NA"}
  else if (min(x,na.rm=T)==max(x,na.rm=T)){"Uniform"}
  else {"Non-Uniform"}}

# Make the filter
uniformity_check <- apply(genotypes.mx,1,uniformity_check.udf)
summary(as.factor(uniformity_check))
non_uniform_sites <- uniformity_check == "Non-Uniform"

# Remove variants with uniform genotypes accross all samples
genotypes.mx <- genotypes.mx[non_uniform_sites,]
variants.df <- variants.df[non_uniform_sites,]

# Check result
dim(genotypes.mx)
dim(variants.df)

table(phenotypes.df$cc)
table(phenotypes.df$danish)
table(phenotypes.df[,c("cc","danish")])

# Clean-up
rm(uniformity_check.udf, uniformity_check, non_uniform_sites)

```

# Check data

```{r}

ls()

dim(genotypes.mx)
dim(phenotypes.df)
dim(variants.df)

sum(colnames(genotypes.mx) != rownames(phenotypes.df))
sum(rownames(genotypes.mx) != rownames(variants.df))

```

# Save results

```{r}

save.image(file.path(data_folder, "s04_exclude_danish.RData"))

```

# Final section

```{r}

ls()
sessionInfo()
Sys.time()
gc()

```
